name: backend-test
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  backend-test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Running Tests
      run: make test
